### ISSUE TITLE
from .layers.drop import DropPath

### ISSUE THREAD

**Issue by zkx-sust** [Alibaba-MIIL/STAM#1]
This is great work and I want to read the code.
But I am a rookie on pytorch, I can`t find DropPath, to_2tuple, register_model module, can you tell me where to find them?
Thanks a lot!

**Comment by giladsharir** [comment]
The code has been updated with some fixes.  Please checkout the new version

**Comment by zkx-sust** [comment]
Thanks a lot!😬

---Original---
From: ***@***.***&gt;
Date: Thu, Apr 1, 2021 02:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Alibaba-MIIL/STAM] from .layers.drop import DropPath (#1)




 
The code has been updated with some fixes.  Please checkout the new version
