### ISSUE TITLE
Pretrain weights from the ImageNet

### ISSUE THREAD

**Issue by villawang** [Alibaba-MIIL/STAM#14]
Hi,

Thanks for sharing this amazing work. I am just wondering where I can get the ImageNet pretrained weights as I see that Kinetics uses pretrained ImageNet weights for training in the paper. I would like to retrain the model.

**Comment by giladsharir** [comment]
Hi 
thanks for your interest in this work.  I took the pretrained weights from this [repo](https://github.com/Alibaba-MIIL/ImageNet21K).  The link to the pretrained ViT-b weights is provided [link](https://miil-public-eu.oss-eu-central-1.aliyuncs.com/model-zoo/ImageNet_21K_P/models/vit_base_patch16_224_miil_21k.pth)

**Comment by villawang** [comment]
Thanks for your reply. I will give it try.
