### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by OValery16** [Alibaba-MIIL/STAM#4]
Dear researchers, 

Thank you for this very nice piece of of work. 

Can you also provide the code you use for the training ? 

Without it, it is impossible to reproduce your results, and validate your conclusion.

Best regards,

**Comment by Andy1621** [comment]
Agree!

**Comment by giladsharir** [comment]
Thanks for taking interest in this work. 
Due to legal issues, we can't release the training code at the moment.
