### ISSUE TITLE
some training hyperparameters about kinetics400

### ISSUE THREAD

**Issue by lwdoubles** [Alibaba-MIIL/STAM#6]
I want to know hyperparameters in Kinetics400(root=source, step_between_clips=args.step_between_clips, frames_per_clip=args.frames_per_clip, frame_rate=args.frame_rate)

**Comment by giladsharir** [comment]
depends on which version you want to train.  If you're interested in STAM_16 for instance, then frames_per_clip = 16, frame_rate = 1.6,  and step_between_clips = 100
